name: Build For Deployment
on: 
    push:
        branches:
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
    build:
        uses: slaclab/eed-java-backend-example-deployment/.github/workflows/build-test-create.yml@main
        secrets: inherit

