# name: BuildAndTest
# on: 
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     branches:
#       - main
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
# jobs:
#     build:
#         uses: <repo>/<project>/.github/workflows/build.yml@main
#         secrets: inherit

